// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
 await Firebase.initializeApp(
   options: DefaultFirebaseOptions.currentPlatform,
 );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX87_pXQs6_2vgU6-o_E7v7HLkF9drN40',
    appId: '1:191027756423:web:fbcdab3edee38f771ce722',
    messagingSenderId: '191027756423',
    projectId: 'asklab-56d38',
    authDomain: 'asklab-56d38.firebaseapp.com',
    storageBucket: 'asklab-56d38.firebasestorage.app',
    measurementId: 'G-C094JCS4DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4RraiCj3kbuszpYeuHHGb0ATQRKlM734',
    appId: '1:191027756423:android:e57609c13b7881e41ce722',
    messagingSenderId: '191027756423',
    projectId: 'asklab-56d38',
    storageBucket: 'asklab-56d38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKP8gfOXMCzms2vtwm-3LcvJXhxRJTKOs',
    appId: '1:191027756423:ios:6ed7aa5e5b4887c41ce722',
    messagingSenderId: '191027756423',
    projectId: 'asklab-56d38',
    storageBucket: 'asklab-56d38.firebasestorage.app',
    iosBundleId: 'com.example.asklab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKP8gfOXMCzms2vtwm-3LcvJXhxRJTKOs',
    appId: '1:191027756423:ios:6ed7aa5e5b4887c41ce722',
    messagingSenderId: '191027756423',
    projectId: 'asklab-56d38',
    storageBucket: 'asklab-56d38.firebasestorage.app',
    iosBundleId: 'com.example.asklab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX87_pXQs6_2vgU6-o_E7v7HLkF9drN40',
    appId: '1:191027756423:web:60ab0bff4519ec8c1ce722',
    messagingSenderId: '191027756423',
    projectId: 'asklab-56d38',
    authDomain: 'asklab-56d38.firebaseapp.com',
    storageBucket: 'asklab-56d38.firebasestorage.app',
    measurementId: 'G-VJ77XBKZJ9',
  );
}
